# Generated by Django 3.0.8 on 2020-09-28 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0003_listings_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='bid',
            field=models.FloatField(),
        ),
    ]
