# Generated by Django 3.0.8 on 2020-09-28 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0005_listings_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listings',
            name='date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
