# Generated by Django 3.0.8 on 2020-09-28 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0007_auto_20200928_0741'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bid',
            old_name='listingId',
            new_name='listing',
        ),
    ]
